# Generated by Django 5.0.6 on 2024-05-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.CharField(max_length=256)),
                ('negative_prompt', models.CharField(max_length=256)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('num_inference_steps', models.IntegerField()),
                ('guidance_scale', models.FloatField()),
                ('seed', models.IntegerField()),
            ],
        ),
    ]
