# Generated by Django 5.0.6 on 2024-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dreamboothmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='width',
        ),
        migrations.AlterField(
            model_name='dreamboothmodel',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dreamboothmodel',
            name='token',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
