# Generated by Django 5.0.6 on 2024-06-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_dreamboothmodel_batch_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DreamboothModel',
        ),
    ]
