# Generated by Django 5.0.6 on 2024-06-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_dreamboothmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='dreambooth',
            field=models.BooleanField(default=False),
        ),
    ]
