# Generated by Django 5.0.6 on 2024-06-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_generatedimage_dreambooth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='seed',
        ),
    ]
